### ISSUE TITLE
meteor-base

### ISSUE THREAD

**Issue by onhate** [disney/meteor-base#1]
Hi,
I like the way you structured this meteor build using docker, specially with multi stage, that's genius! My question is if it would be possible to make meteor-base available on docker registry, so others can benefit from it easily, just using the multi stage sample.

Thanks.

**Comment by onhate** [comment]
Looking forward for this!

**Comment by onhate** [comment]
awesome! thanks!

**Comment by GeoffreyBooth** [comment]
https://forums.meteor.com/t/meteor-docker-image-for-multistage-docker-builds/44908
