### ISSUE TITLE
Certain node_modules libraries break because of alpine vs ubuntu base images

### ISSUE THREAD

**Issue by MastroLindus** [disney/meteor-base#104]
Hi,

First of all thank you very much for publishing this repo, it is very appreciated!
Now to the issue:
Certain node modules like Sharp won't currently work if you have them in your meteor project.
That's because the base image uses ubuntu as base, and that's where the Sharp dependency gets built with npm install, while the final images use node-alpine to run. Sharp will complain about it because of the difference between the build libraries and the runtime ones.
It is easy to deal with it by using a non-alpine image of node, but I guess it would be better to fix it differently or at least document it somewhere.
Cheers!

**Comment by GeoffreyBooth** [comment]
Are you using https://github.com/disney/meteor-base/blob/main/example/app-with-native-dependencies.dockerfile? There are three base images there; the middle one compiles your app dependencies in an Alpine context. This is mentioned in https://github.com/disney/meteor-base#step-1-bootstrap-dockerfile-from-template.

If this doesn’t address your issue, please provide a minimal reproduction. You can also search this repo for issues related to “bcrypt,” as that’s a very commonly used native dependency that has tripped people up in the past.

**Comment by GeoffreyBooth** [comment]
If you look at https://github.com/disney/meteor-base/blob/791bcd03e2f694e7b132dcb7f6f529e57fedcd81/example/app-with-native-dependencies.dockerfile#L34, your dependencies are recompiled under Alpine as part of `app-with-native-dependencies.dockerfile`. That won’t help if the dependency itself won’t compile under Alpine or run successfully under Alpine, or if it ships just a binary without sources that can be compiled, which sounds like the edge case you’re mentioning. In that case, another file like `app-with-native-dependencies-debian.dockerfile` could perhaps be created that changes both Alpine images (the intermediate build image and the runtime image) to Debian, similar to your changes in https://github.com/Refty/lemverse/commit/68f5ff93b35bd6a19781998cd3c145d284024554. If you’d like to try this out and open a PR, including updates to the README and tests, I’ll review it.
