### ISSUE TITLE
Weird permission notification and when running docker up

### ISSUE THREAD

**Issue by lucasdavid** [disney/meteor-base#11]
I'm copied your Dockerfile, docker-compose.yml and .dockerignore to the root of a project of mine. The project runs fine in my computer, but when I run `docker-compose up` in the server (I ssh into the server before running locally), I get the following message and the process apparently hangs:
```shell
Building app
Step 1/14 : FROM geoffreybooth/meteor-base:1.7.0.3
 ---> ac044469284c
Step 2/14 : COPY ./app/package*.json $APP_SOURCE_FOLDER/
 ---> Using cache
 ---> a5d65c4a3e42
Step 3/14 : RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh
 ---> Using cache
 ---> 24c301e78737
Step 4/14 : COPY ./app $APP_SOURCE_FOLDER/
 ---> Using cache
 ---> 6700ddb24352
Step 5/14 : RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh
 ---> Running in a6e2ad239e11

[-] Building Meteor application bundle...


Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local


Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local
```

Would you know how to fix this? I added the following to the environment section in the `docker-compose.yml` file, but it seems it had no effect:
```yml
    ...
    environment:
      ...
      METEOR_NO_RELEASE_CHECK: 'true'
      METEOR_ALLOW_SUPERUSER: 'true'
```

---

```shell
Docker version 18.06.0-ce, build 0ffa825
docker-compose version 1.23.2, build 1110ad01
```

**Comment by GeoffreyBooth** [comment]
If you look at https://github.com/disney/meteor-base/blob/master/src/docker/build-meteor-bundle.sh, it’s running `meteor build` on your files that it copies into the image. So presumably there’s a permissions or file ownership issue with your files on the building machine.

**Comment by Philip-Nunoo** [comment]
Any solution for this?

**Comment by GeoffreyBooth** [comment]
The error means what it says: you have a permissions issue with your application files that get copied into the image. You don't see that issue when you run outside of Docker because you're running as a user with root privileges. Inspect the permissions and owners of your files on the machine where you're building the Docker image.
