### ISSUE TITLE
Include 2.5.7-beta.0

### ISSUE THREAD

**Issue by donstephan** [disney/meteor-base#111]
Can you support `2.5.7-beta.0`?. It isn't going to be released but `2.5.6` builds so slow and `2.5.7-beta.0` has an update to babel that vastly reduces the compile time. Since 2.6+ is such a bit step in terms of breaking changes, it would be nice to have `2.5.7-beta.0` in here. Understandable if you don't want to include beta version though.

**Comment by GeoffreyBooth** [comment]
Hi, we're already at 2.7.1; why would you need a beta version of a version that's already been released?

But also yes, I don't want to support beta/prerelease versions. You can fork this repo and create such an image yourself rather trivially.
