### ISSUE TITLE
Proxy Configuration

### ISSUE THREAD

**Issue by nspangler** [disney/meteor-base#114]
I am having a terrible time doing a docker build with this project behind our corporate proxy. Here are my attempts:

1.  Attempt: I run `docker build` without setting any sort of proxy setting anywhere. Result: FAILED - `ERROR [internal] load metadata for docker.io/geoffreybooth/meteor-base:2.7.1 `  - this makes sense.
2. Attempt: I set our corporate proxy settings in the Mac OSX Docker Desktop UI under the proxy settings. Result: FAILED - I am able to get to the `/docker/build-app-npm-dependencies.sh` but it fails with an error `request to https://registry.npmjs.org failed, reason: getaddrinfo EAI_AGAIN my.proxy` . 
3. Attempt: I set proxy settings in the Dockerfile before the build npm dependencies script. `ENV http_proxy http://my.proxy 
ENV https_proxy https://my.proxy`. Result: FAILED - Same as above.
4. Attempt: I set proxy settings in the build args flag of the docker build `docker build --build-arg http_proxy=http://my.proxy  --build-arg https_proxy=http://my.proxy  -t my_project . `. Result: FAILED - Same as 2.

Any thought on what else I should try? Thanks for the great package and help. I assume this is a common problem. I just have not been able to solve this issue.

I have been able to successfully run and execute a build on the same computer when I am not behind my corporate proxy.

**Comment by GeoffreyBooth** [comment]
It sounds like your proxy settings would make it difficult to build _any_ Docker image, not just this one. It’s common for Docker images to reference public images from Docker hub, and to run commands like `npm install` that assume access to the NPM registry, and to pull packages from various Linux registries. Adding extra configuration to every level of where the build process downloads files from external sources would be a significant amount of work. I think you need to find a “higher level” way to route network traffic through your corporate proxy, such as with VPN software.
