### ISSUE TITLE
Error with Vite bundler for Meteor + Vue 3 app

### ISSUE THREAD

**Issue by diavrank** [disney/meteor-base#129]
Hi, I get this error when I try to build a meteor app with Vue 3 by using the `vite:bundler` package.

````shell
root@meteor-vue:/opt/theory-swe# docker-compose build app
Building app
Step 1/25 : FROM geoffreybooth/meteor-base:2.8.0
 ---> a5e9478d2a9c
Step 2/25 : COPY ./package*.json $APP_SOURCE_FOLDER/
 ---> 4a797b015d84
Step 3/25 : RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh
 ---> Running in 04911bcba75e

[-] Installing app NPM dependencies...


> protobufjs@6.11.2 postinstall /opt/src/node_modules/protobufjs
> node scripts/postinstall


> bcrypt@5.0.1 install /opt/src/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/opt/src/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote

> esbuild@0.15.13 postinstall /opt/src/node_modules/esbuild
> node install.js

added 452 packages in 18.495s
Removing intermediate container 04911bcba75e
 ---> 10ea7e4634b6
Step 4/25 : COPY . $APP_SOURCE_FOLDER/
 ---> b624cc8ca711
Step 5/25 : RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh
 ---> Running in 5fb714dbc722

[-] Building Meteor application bundle...

    This container can use 7946M memory in total.
    If it aborts with an out-of-memory (OOM) or ‘non-zero exit code 137’ error message,
    please increase the container’s available memory.

    See https://github.com/meteor/meteor/issues/9568 for details.


Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

⚡️ Building packages to make them available to export analyzer...
⚡️ Packages built (67684.24ms)
⚡️ Building with Vite...
Errors prevented bundling:
While loading plugin `vite` from package `vite:bundler`:
internal/child_process.js:1107:20: Command failed with ENOENT: node
/opt/src/node_modules/.meteor-vite-build-worker.mjs
spawnSync node ENOENT
at Object.spawnSync (internal/child_process.js:1107:20)
at Object.spawnSync (child_process.js:776:24)
at execaSync (packages/vite/build.js:375:2)
at packages/vite/build.js:262:18
at module (packages/vite/build.js:375:2)
at fileEvaluate (packages/modules-runtime.js:336:7)
at Module.require (packages/modules-runtime.js:238:14)
at require (packages/modules-runtime.js:258:21)
at packages/vite/build.js:375:2
at packages/vite/build.js:375:2


ERROR: Service 'app' failed to build: The command '/bin/sh -c bash $SCRIPTS_FOLDER/build-meteor-bundle.sh' returned a non-zero code: 1
````

However, if I build the app locally, it works:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/39581375/203905022-460af53e-332c-45eb-ae88-5d20e10ecc36.png">

is there a missing package/program that I have to install in alpine to avoid this error?

**Notes:**
- Meteor 2.8.0
- VM with Ubuntu 20.04
- node:14.20.1-alpine

**Comment by diavrank** [comment]
cc: @Akryum

**Comment by Akryum** [comment]
Looks like it fails writing the build script

**Comment by GeoffreyBooth** [comment]
`internal/child_process.js:1107:20: Command failed with ENOENT: node` looks like the Vite build script is running a `node` command that assumes `node` is in the system `PATH`, which it is on your local machine but isn’t on that build container (because it’s using the internal Meteor `node`). You could figure out where Meteor’s `node` is saved and add that to the `PATH` for that stage’s image.

Alternatively, @Akryum could update the build script to replace `node` with `meteor node`. This would probably be a better long-term solution, as it would ensure that whatever build script work is happening is done with the same Node version as Meteor is running, which is probably very different from your global version (like if you’re running Node 19 globally while Meteor uses Node 14).

**Comment by GeoffreyBooth** [comment]
Closing as unlikely an issue with this project, will reopen if you investigate and determine otherwise.

**Comment by diavrank** [comment]
Fortunately, there is already a PR to solve this problem. Result is [here](https://github.com/Akryum/meteor-vite/pull/22#issuecomment-1416834208). Thanks to @red-meadow
