### ISSUE TITLE
TypeError in docker

### ISSUE THREAD

**Issue by sygi** [disney/meteor-base#136]
I have a meteor project that works when I run it with `meteor run`, but when I run it through docker it correctly connects to an external MongoDB database, but the website doesn't load, and I see two errors in the inspector:
```
ERROR TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```
and
```
ERROR Error: Uncaught (in promise): TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

It looks like the `<head>` part of the HTML got rendered, but body wasn't filled correctly. Any idea what could be going on here?

**Comment by GeoffreyBooth** [comment]
I’m sorry, this isn’t a support forum to help you debug your app. If you find a bug related to this Docker image, please open an issue for that; otherwise, there are other forums for asking for general help.
