### ISSUE TITLE
Add ssh to base image to install dependencies directly from Git/Github

### ISSUE THREAD

**Issue by jenshaase** [disney/meteor-base#141]
When running `meteor npm ci` and the `package-lock.json` contains a dependencies that directly references a git repository, npm will use ssh to download the package. However, ssh is missing in this image and it leads to the following error:

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/meteor/readable-stream.git
npm ERR! 
npm ERR! error: cannot run ssh: No such file or directory
npm ERR! fatal: unable to fork
```

**Comment by GeoffreyBooth** [comment]
Would you like to propose a PR? You probably need to add it here: https://github.com/disney/meteor-base/blob/81f4dac7b379266535132fcf17b0dc4e267d1e8a/src/Dockerfile#L17
