### ISSUE TITLE
app not available at localhost

### ISSUE THREAD

**Issue by phipsss** [disney/meteor-base#142]
hey, i tried using this meteor base to run it inside a docker container, but for some reason the app is not available at localhost port 3000 even tho the build finishes and both the mongo aswell as the app containers are running. It seems like the app doesn´t finish starting. Here is a screenshot of the console after it stopped building.
![Screenshot 2023-06-05 140508](https://github.com/disney/meteor-base/assets/121243317/87ba180a-dd64-42d6-aff6-8f8be90a8784)

I tried it with both docker files but it´s the same result. I even tried the demo meteor app to make sure it´s not an issue with the app I originally tried to pack into the container, but it shows the same result. Maybe somebody can point me into the right direction of what i´m missing or doing wrong

**Comment by GeoffreyBooth** [comment]
Closing as I’m not in a position to provide technical support. If you find an issue with this image specifically, please let me know.
