### ISSUE TITLE
Missing 2.8.2 tag on docker hub

### ISSUE THREAD

**Issue by jlugner** [disney/meteor-base#145]
2.8.2 seems to be missing from docker hub. I'm running into som M1-related issues in building the version on my own. I'll give it another go once I've managed to resolve that, unless someone else can get it done before 😄

**Comment by GeoffreyBooth** [comment]
2.8.2 isn’t on our versions list: https://github.com/disney/meteor-base/blob/main/versions.sh. But you can make a PR to add it, like the other recent PRs for new versions. See https://github.com/disney/meteor-base/tree/main#adding-a-new-meteor-version
