### ISSUE TITLE
update.sh adds duplicated lines to support.sh

### ISSUE THREAD

**Issue by bladerunner2020** [disney/meteor-base#155]
When I run ./update.sh --meteor-version 2.15 --node-version 14.21.4 I got multiple lines with 2.15 in support.sh

![image](https://github.com/disney/meteor-base/assets/13632647/231345c6-cf34-4a28-ae2e-415ff234ac7a)

This is because of this line: 
`do_sed $"s|'${node_version}'|'${node_version}'\\n	elif [[ \"\$1\" == ${new_meteor_version} ]]; then node_version='${new_node_version}'|" ./support.sh`

I think that $ before sed's substitute command is treated as address not as the latest occurrence.

**Comment by GeoffreyBooth** [comment]
Fixed by #156
