### ISSUE TITLE
Development version?

### ISSUE THREAD

**Issue by ben-obringer** [disney/meteor-base#158]
Hello. This is more of a question, so apologies if this isn't the right place to ask. Is there a development version for the Docker setup? Basically I want to have a local development Docker setup that is is as close as possible to the production version.

**Comment by GeoffreyBooth** [comment]
You can always run your app on your local machine using this image. See `test.sh`, that’s exactly what it does.

It’s not very _convenient_ to develop this way; every code change means rebuilding the image. But if you just want to test what should be finished code before deployment, it’s possible today.
