### ISSUE TITLE
Image used in examples does not exist

### ISSUE THREAD

**Issue by digitalextremist** [disney/meteor-base#169]
It seems the latest tag available is `3.0.2` but the example uses `3.0.4`
https://github.com/disney/meteor-base/blob/66ae62496c7619d8a6d5b4a1675adf3fcbce7d56/example/default.dockerfile#L2

`README.md` does warn about this, but then uses non-existent tag:
- https://github.com/disney/meteor-base?tab=readme-ov-file#quickstart
- https://hub.docker.com/r/geoffreybooth/meteor-base/tags

However there was this pull request merged, so there is likely not an image pushed live to the tag referenced?

https://github.com/disney/meteor-base/pull/168

**I appreciate this package very much!**

**Comment by GeoffreyBooth** [comment]
They’re there now.
