### ISSUE TITLE
Native dependencies dockerfile breaks; distutils removed from Python 3.12

### ISSUE THREAD

**Issue by digitalextremist** [disney/meteor-base#170]
This might be unnecessary to resolve per something I am missing, but being in a hurry and not very interested in `python` right now, I patched my custom dockerfile to workaround a `python3` module problem.

This is an often reported issue all over the place. I adapted a solution to the `apk` case in `meteor-base`  below.

Problem: https://docs.python.org/3/whatsnew/3.12.html#summary-release-highlights

Removal of `distutils` causes a fatal error at time of build, with a ton of preamble and postmortem log spam removed:

```
npm error npm error ModuleNotFoundError: No module named 'distutils'
```

---

As temporary/workaround solution add `py3-setuptools` after `python3` here:

https://github.com/disney/meteor-base/blob/66ae62496c7619d8a6d5b4a1675adf3fcbce7d56/example/app-with-native-dependencies.dockerfile#L26

Workaround above is per advice:
- https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed/76691103#76691103
- But since "environment externally managed" used `apk` instead: https://pkgs.alpinelinux.org/package/edge/main/x86/py3-setuptools

---

I am not confident enough in `python` oriented under-rug items or how/why this actually matters to recommend as a pull request, but the above is what one would involve if it did in fact matter.

**Comment by mcorbelli** [comment]
Same solution
![Screenshot 2024-10-24 alle 12 01 52](https://github.com/user-attachments/assets/6b010c1d-7450-44ac-bbc2-eba0e214a110)

**Comment by GeoffreyBooth** [comment]
The build still works for me. If you’d like to post a PR to improve this part of the Dockerfile, that would be welcome.
