### ISSUE TITLE
Images from 1.9 to (at least) 2.15 are broken

### ISSUE THREAD

**Issue by Pavel-R** [disney/meteor-base#171]
Switching to new base ubuntu image (24.04) with default python version 3.12 brokes node-gyp installation process. For python  =< 3.10 mode `U` for file opening operation was simply ignored. Now It's throwing exception.

```
#13 18.39   File "/root/.meteor/packages/meteor-tool/.2.15.0.14dvwv6.8tc8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
#13 18.39     build_file_contents = open(build_file_path, 'rU').read()
#13 18.39                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#13 18.39 ValueError: invalid mode: 'rU' while trying to load binding.gyp
#13 18.40 gyp ERR! configure error 
```

**Comment by GeoffreyBooth** [comment]
These images are always built with latest Ubuntu. If your project requires a particular version of Python, you should use this as a base and install the correct version of Python that you require.
