### ISSUE TITLE
App doesn't come up in browser

### ISSUE THREAD

**Issue by Quantmatic** [disney/meteor-base#19]
I get an issue with 1.8.1 where the build is successful, but the app does not come up in browser.

I did `docker-compose up --build` from the example dir
[dcompose_log.txt](https://github.com/disney/meteor-base/files/3600055/dcompose_log.txt)

The images come up in docker, but app does not load.

Can you confirm that docker-compose works with meteor 1.8.1?

It does come up if I run app directly with the Ubuntu Host Meteor, so I'm not sure where the bug is.

**Comment by GeoffreyBooth** [comment]
Yes, the image works for 1.8.1 and docker-compose. You can verify with one of the Meteor starter apps.

**Comment by mandy169** [comment]
I cannot see the app in browser, event with the example app in the repo. In the console I didn't see errors.

`Creating example_mongo_1 ... done
Creating example_app_1   ... done
Attaching to example_mongo_1, example_app_1
mongo_1  | 2019-10-27T22:19:34.637+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
app_1    | Connecting to MongoDB...
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=489523aadb16
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] db version v4.2.1
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] git version: edf6d45851c0b9ee15548f0f847df141764a317e
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] modules: none
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] build environment:
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten]     distarch: x86_64
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
mongo_1  | 2019-10-27T22:19:34.826+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" }, storage: { engine: "wiredTiger" } }
mongo_1  | 2019-10-27T22:19:34.826+0000 I  STORAGE  [initandlisten]
mongo_1  | 2019-10-27T22:19:34.827+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1  | 2019-10-27T22:19:34.827+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1  | 2019-10-27T22:19:34.827+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1358M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_ma
nager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
mongo_1  | 2019-10-27T22:19:35.629+0000 I  STORAGE  [initandlisten] WiredTiger message [1572214775:629831][1:0x7f1a641bcb00], txn-recover: Set global recovery timestamp: (0,0)
mongo_1  | 2019-10-27T22:19:35.933+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1  | 2019-10-27T22:19:36.155+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongo_1  | 2019-10-27T22:19:36.288+0000 I  CONTROL  [initandlisten]
mongo_1  | 2019-10-27T22:19:36.288+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1  | 2019-10-27T22:19:36.288+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1  | 2019-10-27T22:19:36.288+0000 I  CONTROL  [initandlisten]
mongo_1  | 2019-10-27T22:19:36.326+0000 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 2b78ff52-587c-4f66-942e-ac5078f61d94 and options: { uuid: UUID("2b78ff52-587c-4f66-942e-ac5078f61d94") }
mongo_1  | 2019-10-27T22:19:36.647+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns admin.system.version
mongo_1  | 2019-10-27T22:19:36.651+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
mongo_1  | 2019-10-27T22:19:36.651+0000 I  COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.2
mongo_1  | 2019-10-27T22:19:36.652+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
mongo_1  | 2019-10-27T22:19:36.663+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongo_1  | 2019-10-27T22:19:36.670+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
mongo_1  | 2019-10-27T22:19:36.672+0000 I  STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: fed7f9bd-d29f-4d2e-9779-07fffc6e5161 and options: { capped: true, size: 10485760 }
mongo_1  | 2019-10-27T22:19:36.930+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns local.startup_log
mongo_1  | 2019-10-27T22:19:36.930+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
mongo_1  | 2019-10-27T22:19:36.931+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1  | 2019-10-27T22:19:36.941+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
mongo_1  | 2019-10-27T22:19:36.941+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
mongo_1  | 2019-10-27T22:19:36.941+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
mongo_1  | 2019-10-27T22:19:36.941+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
mongo_1  | 2019-10-27T22:19:36.983+0000 I  NETWORK  [listener] connection accepted from 172.19.0.3:59042 #1 (1 connection now open)
mongo_1  | 2019-10-27T22:19:36.983+0000 I  NETWORK  [listener] connection accepted from 172.19.0.3:59044 #2 (2 connections now open)
mongo_1  | 2019-10-27T22:19:36.985+0000 I  NETWORK  [listener] connection accepted from 172.19.0.3:59046 #3 (3 connections now open)
mongo_1  | 2019-10-27T22:19:36.985+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
mongo_1  | 2019-10-27T22:19:36.985+0000 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: 585b4088-7024-4771-b62e-a59d50deb230 and options: { uuid: UUID("585b4088-7024-4771-b62e-a59d50deb230") }
mongo_1  | 2019-10-27T22:19:37.000+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
mongo_1  | 2019-10-27T22:19:37.008+0000 I  NETWORK  [conn3] received client metadata from 172.19.0.3:59046 conn3: { driver: { name: "nodejs", version: "3.0.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.184-linuxkit" }, platform: "Node.js v8.16.2, LE, mongodb-core: 3.0.7" }
mongo_1  | 2019-10-27T22:19:37.014+0000 I  NETWORK  [conn3] end connection 172.19.0.3:59046 (2 connections now open)
mongo_1  | 2019-10-27T22:19:37.255+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
mongo_1  | 2019-10-27T22:19:37.496+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 } using method: Hybrid
mongo_1  | 2019-10-27T22:19:37.496+0000 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 500 megabytes of RAM
mongo_1  | 2019-10-27T22:19:37.496+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
mongo_1  | 2019-10-27T22:19:37.496+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
mongo_1  | 2019-10-27T22:19:37.538+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
mongo_1  | 2019-10-27T22:19:37.579+0000 I  COMMAND  [LogicalSessionCacheRefresh] command config.system.sessions command: createIndexes { createIndexes: "system.sessions", indexes: [ { key: { lastUse: 1 }, name: "lsidTTLIndex", expireAfterSeconds: 1800 } ], $db: "config" } numYields:0 reslen:114 locks:{ Para
llelBatchWriterMode: { acquireCount: { r: 2 } }, ReplicationStateTransition: { acquireCount: { w: 3 } }, Global: { acquireCount: { r: 1, w: 2 } }, Database: { acquireCount: { r: 1, w: 2, W: 1 } }, Collection: { acquireCount: { r: 4, w: 1, R: 1, W: 2 } }, Mutex: { acquireCount: { r: 3 } } } flowControl:{ acq
uireCount: 1 } storage:{} protocol:op_msg 594ms
`

**Comment by Quantmatic** [comment]
It's running in server mode, there is no client.

To check if it worked you need to login into the container with docker exec, and do the top cmd

If you see node running, it's working

Sent from ProtonMail mobile

-------- Original Message --------
