### ISSUE TITLE
Unable to connect to mongodb

### ISSUE THREAD

**Issue by mdy405** [disney/meteor-base#22]
First of all thx for this great Meteor image ... but when using "start": "meteor run --settings ./settings.json" app unable to connect to mongodb ? and work fine without run settings...

**Comment by GeoffreyBooth** [comment]
Is your settings file overriding `MONGO_URL`? Is the settings file even getting copied into the right place inside the container? Without knowing what changes you’ve made to the example project in this repo, I can’t diagnose what’s wrong.

If you can provide an example repo that shows a bug in this image, I’d be happy to fix it. Unfortunately I don’t have time to help troubleshoot your app.
