### ISSUE TITLE
Exit code 139

### ISSUE THREAD

**Issue by l3aconator** [disney/meteor-base#3]
Okay, I lied, I am having an issue.

I think it might be a perms problem, the app builds beautifully, but when firing off calls to meteor using the accounts package, the container exits with code 139. I have been banging my head against the wall all day. 

I noticed the other older dockerfiles add a separate user and then change the owner to said user. I ran my app in docker rjshimko/meteor-launchpad which adds the seperate user and it works fine with the accounts package, but the file is huge. I have been playing with adding a user and modifying the perms, but still no dice. I am a docker noob. Do you have any advice or solutions to this problem?

**Comment by GeoffreyBooth** [comment]
Sorry, I don’t know. My app uses Meteor’s accounts and it works fine.

**Comment by preethamnayak** [comment]
I am trying to run meteor docker using DC/OS marathon and I am getting Container exited with status 139, failed to accept socket loop error. Do you have any solutions ?

**Comment by gregory** [comment]
for anyone landing here, this is related to an issue with [bcrypt issue](https://github.com/kelektiv/node.bcrypt.js/issues/528) on alpine.
Related to [another issue](https://github.com/disney/meteor-base/issues/18) on this repo.
