### ISSUE TITLE
Could use with Meteor 1.3x, 1.4.x, 1.5x?

### ISSUE THREAD

**Issue by thearabbit** [disney/meteor-base#32]
Could use with Meteor 1.3x, 1.4.x, 1.5x?

**Comment by GeoffreyBooth** [comment]
Perhaps, I haven't tested. Please let me know what you find 😀 You'll need to use the build-with-native-dependencies Dockerfile, as those older versions of Meteor lack the new version of Fibers that includes an Alpine-compatible binary so therefore it must be compiled.

**Comment by thearabbit** [comment]
thanks for your reply.
Should try with this file `app-with-native-dependencies.dockerfile`
```js
# The tag here should match the Meteor version of your app, per .meteor/release
FROM geoffreybooth/meteor-base:1.9

# Copy app package.json and package-lock.json into container
COPY ./app/package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

# Copy app source into container
COPY ./app $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh


# Use the specific version of Node expected by your Meteor release, per https://docs.meteor.com/changelog.html; this is expected for Meteor 1.9
FROM node:12.14.0-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker

# Install OS build dependencies, which we remove later after we’ve compiled native Node extensions
RUN apk --no-cache --virtual .node-gyp-compilation-dependencies add \
		g++ \
		make \
		python \
	# And runtime dependencies, which we keep
	&& apk --no-cache add \
		bash \
		ca-certificates

# Copy in entrypoint
COPY --from=0 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle
COPY --from=0 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh --build-from-source \
	&& apk del .node-gyp-compilation-dependencies

# Start app
ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["node", "main.js"]
```
Have any edit this file???

**Comment by thearabbit** [comment]
But I checked available tag `1.6` (lowest)!

**Comment by GeoffreyBooth** [comment]
> But I checked available tag `1.6` (lowest)!

Yes, you need to build the other images. Clone this repo and edit `versions.sh` with the versions you want to support, then run `build.sh` to build them locally. Then you'll have e.g. `geoffreybooth/meteor-base:1.4.0` in your local Docker registry, and you could edit a fork of `app-with-native-dependencies.dockerfile` to `FROM` that image.

Those earlier versions of Meteor used older versions of Node, so you'll also need to change the version of Node in that `FROM` line.

**Comment by thearabbit** [comment]
Very clear.
Other hand, we could use with any `meteor docker images` such as
- kadirahq/meteord
- abernix/meteord:base
- abernix/meteord:node-8.4.0-base
- zodern/meteor:root ......
?????

**Comment by GeoffreyBooth** [comment]
> Other hand, we could use with any `meteor docker images` such as

Yes, but then you lose the advantages described in https://github.com/disney/meteor-base/blob/master/README.md#why-this-image-instead-of-some-others

**Comment by thearabbit** [comment]
I mean that, I use this image with your `Dockerfile`
```js
// Dockerfile
# The tag here should match the Meteor version of your app, per .meteor/release
FROM abernix/meteord:base // -----  Custom any docker image

# Copy app package.json and package-lock.json into container
COPY ./package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

# Copy app source into container
COPY ./ $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh


# Use the specific version of Node expected by your Meteor release, per https://docs.meteor.com/changelog.html; this is expected for Meteor 1.9
# How to check:  meteor node --version
FROM node:4.6.2-alpine

.......

```
And then I run `docker build -t yourname/app .`
But don't work
