### ISSUE TITLE
Manifest for geoffreybooth/meteor-base:1.10.2 not found

### ISSUE THREAD

**Issue by AymericBethencourt** [disney/meteor-base#46]
Hey,

Thank you very much for this docker image, this is very useful and made my life much simpler! 👍 
Just one detail, following your update to 1.10.2 today, you did not create the image on docker hub, I get: 
 
ERROR: Service 'app' failed to build: manifest for geoffreybooth/meteor-base:1.10.2 not found: manifest unknown: manifest unknown

**Comment by AymericBethencourt** [comment]
I see this has been fixed, thanks :)

**Comment by GeoffreyBooth** [comment]
Sorry the push takes a long time since it repushes all versions. Happy to help 😄
