### ISSUE TITLE
Entrypoint file polls for a Mongo connection forever

### ISSUE THREAD

**Issue by tomcardoso** [disney/meteor-base#49]
Think I've run into a bug. My docker-compose file, which is mostly the same as your default one, specifies an app and a mongo database (and a headless browser, but that's beside the point).

After building, if I run `docker-compose  -f docker-compose.production.yml up`, here's what I see:

```sh
$ docker-compose -f docker-compose.production.yml up
Creating network "chart-tool_chart-tool-network" with the default driver
Creating chart-tool_mongo_1       ... done
Creating chart-tool_browserless_1 ... done
Creating chart-tool_app_1         ... done
Attaching to chart-tool_browserless_1, chart-tool_mongo_1, chart-tool_app_1
app_1          | Connecting to MongoDB...
app_1          | (node:6) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```

And it just waits to connect… forever. I waited 10min earlier with no connection. Oddly, running `docker-compose -f docker-compose.production.yml run --service-ports app bash` does actually make a Mongo connection:

```sh
$ docker-compose -f docker-compose.production.yml run --service-ports app bash
Starting chart-tool_mongo_1 ... done
Starting chart-tool_browserless_1 ... done
Connecting to MongoDB...
(node:7) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Starting app...
bash-5.0# exit
exit
```

That said, I think I might have an idea of what's going on. I tested the Node script from the connect-to-mongo.sh, and running it independently results in a module missing error. Is it possible that the `mongodb` package isn't getting installed and available globally?

**Comment by GeoffreyBooth** [comment]
> Is it possible that the mongodb package isn't getting installed and available globally?

The deprecation warning in your output comes from that package. But it was never intended to be available globally, it's installed under the folder where that script is run.

**Comment by tomcardoso** [comment]
Oh, I'm not worried about the deprecation warning. But the fact the `docker-compose up` command never makes it past the Mongo check is a bit frustrating. Could it be a race condition of some sort?

**Comment by GeoffreyBooth** [comment]
Yes, that's why the script is there to poll until Mongo is ready. The Node container usually starts up faster than Mongo in my experience.

**Comment by tomcardoso** [comment]
Right, but what I'm saying is the poll never ends. It just polls and polls and polls…
