### ISSUE TITLE
Document / warn about RAM usage, OOM Errors

### ISSUE THREAD

**Issue by opyh** [disney/meteor-base#50]
Hey @GeoffreyBooth, thanks for your efforts on this project!

This issue is mainly to help people googling for these keyword: OOM, out-of-memory, non-zero exit code 137 error, aborted build.

You might be affected by https://github.com/meteor/meteor/issues/9568.

`meteor build` can use more RAM than you expect. Setting `--max-old-space-size=2048` or similar options for Node won't help (as of Meteor 1.10.2), as the source maps generation is currently using wasm and explicitly switches off GC to mitigate another issue in `node-fibers`.

This issue is frustrating to find in CI setups, where the container is usually just stopped - not all environments display a sensible error message for out-of-memory errors.

Potential solutions: https://github.com/meteor/meteor/issues/9568#issuecomment-642791123

I don't know if Meteor will adopt my suggestion from https://github.com/meteor/meteor/issues/9568#issuecomment-642804069 - but if not, it might be a good idea to add it to this image's build scripts :)

**Comment by GeoffreyBooth** [comment]
Thanks for opening this issue. Do you mind opening a PR with where you think this argument should be in the scripts, or adding a note in the README?

**Comment by opyh** [comment]
Here it is :)
