### ISSUE TITLE
CXX(target) Release.obj.target...

### ISSUE THREAD

**Issue by diavrank** [disney/meteor-base#55]
Hi, is it normal this behavior in 1.11.1 ?

<img width="1059" alt="Screen Shot 2020-09-23 at 4 24 42" src="https://user-images.githubusercontent.com/39581375/93994347-65315200-fd55-11ea-84b3-c437218afe37.png">

These logs didn't happen with 1.10.1 version, so, I wonder if that is normal? Also, I realized that take more time building the image with those logs.

My dockerfile is the following (I just add a little more code for the timezone):

```
# The tag here should match the Meteor version of your app, per .meteor/release
FROM geoffreybooth/meteor-base:1.11.1

# Copy app package.json and package-lock.json into container
COPY ./package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

# Copy app source into container
COPY . $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh

# Use the specific version of Node expected by your Meteor release, per https://docs.meteor.com/changelog.html; this is expected for Meteor 1.9
FROM node:12.18.4-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker
# Runtime dependencies; if your dependencies need compilation (native modules such as bcrypt) or you are using Meteor <1.8.1, use app-with-native-dependencies.dockerfile instead
RUN apk update
RUN apk upgrade
RUN apk --no-cache add \
                bash \
		g++ \
		make \
		python

# Copy in entrypoint
COPY --from=0 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle
COPY --from=0 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh --build-from-source

# Start another Docker stage, so that the final image doesn’t contain the layer with the build dependencies
# See previous FROM line; this must match
FROM node:12.18.4-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker

# Install OS runtime dependencies
RUN apk --no-cache add \
	bash \
	ca-certificates \
    && update-ca-certificates

RUN apk --no-cache add --update tzdata

ENV TZ America/Mexico_City
RUN rm -rf /var/cache/apk/*

# Copy in entrypoint with the built and installed dependencies from the previous image
COPY --from=1 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle with the built and installed dependencies from the previous image
COPY --from=1 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

# Start app
ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["node", "main.js"]

```

**Comment by GeoffreyBooth** [comment]
This is a Meteor question, not related to this Docker image, I think. Those logs look like the Meteor build tool compiling `grpc`, which I presume your app has as a dependency.

The line in red says that `npm` is trying to download a binary for `grpc`, but since none exists for the particular version combination of `grpc` and Node, it compiles a new binary instead. This probably didn’t happen in 1.10 because 1.11.1 uses a new Node version, and I’d guess that `grpc` hasn’t published a binary for that Node version yet; or they published a binary in a new version of `grpc` but your app needs to use that newer version of `grpc` to get it.

**Comment by diavrank** [comment]
I have just realized that is a nested dependency from `google/firestore` which is an optional dependency of `firebase-admin`. I only use **Cloud Storage** but it seems is an all-in-one package ([so far](https://github.com/firebase/firebase-admin-node/issues/1230)). So, for the next version of **SDK FirebaseAdmin** this will be corrected and the build **will take less time**.

**Comment by diavrank** [comment]
I could resolve this issue. I realized that I am using [fcm-notification](https://www.npmjs.com/package/fcm-notification) package which was using an old version of **firebase-admin** (5.11.0). Hence, it was using an old version of **gRPC** which provoked all those lines in the building process. So, I created an [updated version](https://www.npmjs.com/package/@diavrank/fcm-notification) of this package (because the original seems to be unmaintained) and the issue has gone.
