### ISSUE TITLE
Build process getting killed during Heroku deployment, possible OOM issue?

### ISSUE THREAD

**Issue by tomcardoso** [disney/meteor-base#58]
Hi @GeoffreyBooth, me again.

I'm trying to deploy an app using Heroku's build manifest file system (which relies on a heroku.yml file). During the Docker build process, the build is failing on this step:

```
remote: /docker/build-meteor-bundle.sh: line 11:     8 Killed                  meteor build --directory $APP_BUNDLE_FOLDER --server-only
remote: The command '/bin/sh -c bash $SCRIPTS_FOLDER/build-meteor-bundle.sh' returned a non-zero code: 137
```

Could this be an OOM error? If so, any advice on what I can do to get the memory size to behave with Heroku?

**Comment by GeoffreyBooth** [comment]
That's a general Meteor question, please search the Meteor repo or forums and you should find suggestions.

**Comment by tomcardoso** [comment]
This is partly due to the memory limitations of the server-side Docker build, though. Have you run into any issues like this when running meteor-base in the cloud?

**Comment by GeoffreyBooth** [comment]
See https://github.com/disney/meteor-base/issues/50

If that solves your issue, I’ll try to find time to test and merge in that PR.

**Comment by tomcardoso** [comment]
Unfortunately, that change just adds some logging about memory usage… it would certainly be useful as a diagnostic, though.

**Comment by GeoffreyBooth** [comment]
I think the point is that if you’re running out of memory, you need to configure how your Docker container is run to make sure that Docker allocates it more memory. The logging is to tip you off that it might be running without enough memory allocated to it.
