### ISSUE TITLE
Update docker image to Meteor 1.12

### ISSUE THREAD

**Issue by diavrank** [disney/meteor-base#59]
Hello, I noticed that current version of meteor-base is still in 1.11.1 version. So, I wanted to open this issue to remind that there is already a new version of [Meteor](https://github.com/meteor/meteor/releases).

On the other hand, I wonder if I can use `geoffreybooth/meteor-base:1.11.1` to deploy a meteor app in version 1.12?

Greetings.

**Comment by GeoffreyBooth** [comment]
> I wonder if I can use `geoffreybooth/meteor-base:1.11.1`

No, the base image needs updating.

A PR would be pretty easy, if you’d like to submit one. See https://github.com/disney/meteor-base/pull/54 or https://github.com/disney/meteor-base/pull/52 for examples to follow.

**Comment by GeoffreyBooth** [comment]
Published: https://hub.docker.com/layers/geoffreybooth/meteor-base/1.12/images/sha256-6d067dd5721ed318a009a3eeca6d877a43f8320561ad6b054800074d3e6d8916?context=repo

**Comment by diavrank** [comment]
Thank you so much.
