### ISSUE TITLE
ERROR: Service 'app' failed to build: manifest for geoffreybooth/meteor-base:2.1 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by obsidiandevel** [disney/meteor-base#65]
ERROR: Service 'app' failed to build: manifest for geoffreybooth/meteor-base:2.1 not found: manifest unknown: manifest unknown

**Comment by GeoffreyBooth** [comment]
It’s published now. https://hub.docker.com/layers/139959421/geoffreybooth/meteor-base/2.1/images/sha256-7b95bd07cf7478617de8f68f64e08c455742a333a308b39593d1d6c6ce30bd93?context=explore

**Comment by obsidiandevel** [comment]
You're a saint thank you. By the way i got to learn about multi-layer docker images thanks to you. Amazing work.
