### ISSUE TITLE
Example for native dependencies is outdated?

### ISSUE THREAD

**Issue by diavrank** [disney/meteor-base#66]
Hello, I noticed that the example located at `example/app-with-native-dependencies.dockerfile` is still in **2.0.** I don't know why happened this (maybe could be a merge), since in my last commit I updated it to **2.1** 

https://github.com/disney/meteor-base/blob/4990f64fccc8cc1fb73b882391f541ee93534076/example/app-with-native-dependencies.dockerfile#L2

**Comment by GeoffreyBooth** [comment]
Fixed, thanks!
