### ISSUE TITLE
Build Meteor 2.5.3 Docker Image

### ISSUE THREAD

**Issue by nspangler** [disney/meteor-base#97]
Thanks for all of the great work. Your images are fantastic. We recently upgraded our application's Meteor version from 2.5 to 2.5.3 due to a major performance fix. What are your plans for publishing a new docker image for the 2.5.3 release. We aren't able to deploy this vital fix to our production endpoint until the image is available. Thanks.

**Comment by GeoffreyBooth** [comment]
Hi, it’s waiting on https://github.com/meteor/meteor/issues/11791 (see #95). You can ping the Meteor core team there. Basically I’m just waiting on them to publish a new version of their fork of Fibers that contains the Alpine binaries.

**Comment by nspangler** [comment]
@GeoffreyBooth thank's so much for the quick response. I will close this issue and keep an eye on the meteor thread.
