### ISSUE TITLE
External settings file

### ISSUE THREAD

**Issue by inteldon** [disney/meteor-base#98]
How would you reference an external settings.json file in docker-compose.yml?

**Comment by diavrank** [comment]
Hi, afaik, you cannot do that. You have to use a **docker.env** file instead.

`settings.json` file is mainly used for localhost and deploy to Galaxy Hosting.

**Comment by GeoffreyBooth** [comment]
You can mount it as a “volume”, similar to how you see examples online of an Nginx config file being volume-mounted into an Nginx container. [For example](https://stackoverflow.com/a/62683063/223225):

```shell
docker run -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx
```

In your case, edit the `docker-compose.yml` to add a volume with the path to your `settings.json` file, and then use that “volume” in the Meteor app container, mapped to where the app is expecting the file to be.
